{
    'name': 'Follow up',
    'version': '1.1.0',
    # 'summary': 'Beat tracking with auto sequence, customer and employee link',
    'author': '',
    'depends': ['base','crm','sale','sale_project'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/follow_up.xml',
        'views/crm_lead_views.xml',
        # 'views/round_robin_views.xml' ,
        'views/project_project_views.xml',
        'views/sale_order_views.xml' ,
        'views/crm_call_details.xml',
        'views/payment_receipt_report.xml',
    ],
    'installable': True,
    'application': True,
}
